# Generated by Django 3.0.4 on 2020-04-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input_file',
            field=models.ImageField(upload_to='media/input/'),
        ),
    ]
