# Generated by Django 3.0.4 on 2020-04-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20200406_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='input1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.ImageField(blank=True, null=True, upload_to='media/input1/')),
            ],
        ),
        migrations.DeleteModel(
            name='input',
        ),
    ]
